[package]
name = "powerutil"
version = "0.1.0"
edition = "2021"
authors = ["Victor Palade <victor@cloudflavor.io>"]

[dependencies]
dbus = "0.9"
libc = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
structopt = "0.3"
utmp-rs = "0.3"
